#!/usr/bin/env bash
# This script displays info abt subdomains

# Func to fetch and display domain info

show_domain_info() {
	dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'

}

if [ "$#" -eq 2 ]
then
	show_domain_info "$2.$1" "$2"
else
	show_domain_info "www.$1" "www"
	show_domain_info "lb-01.$1" "lb-01"
	show_domain_info "web-01.$1" "web-01"
	show_domain_info "web-02.$1" "web-02"
fi
	