#!/usr/bin/env bash
# Pings IP address passed as argument

# Check if IP address was passed as argument
if [ $# -ne 1 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi
	# Ping IP address 5 times
	ping -c 5 "$1"
