#!/usr/bin/env bash
# This script displays Best school 10 times using the while loop
# If on the 9th iteration, display Best School and then Hi on a new line
x=1
while [ $x -le 10 ]
do
	echo "Best School"
	if [ $x -eq 9 ]
	then
		echo "Hi"
	fi
	(( x++ ))
done
