#!/usr/bin/env bash
# This script displays Best school 10 times using the while loop
# If on the 9th iteration, display Bad luck, for the fourth loop iteration,
# displays good luck and after the 8th iteration, 
# displays Best School for the other iterations
x=1
while [ $x -le 10 ]
do
	if [ $x -eq 4 ]
	then
		echo "Bad luck"
	elif [ $x -eq 8 ]
	then
		echo "Good luck"
	else
		echo "Best School"
	fi
	(( x++ ))
done
