#!/usr/bin/env bash
# This script displays superstitious numbers from 1 to 20
# displays 4, and then on a new line, bad luck from China for the 4th loop iteration
# displays 9, and then on a new line, bad luck from Japan for the 9th loop iteration
# displays 17, and then on a new line, bad luck from Italy for the 17th loop iteration

x=1
while [ $x -le 20 ]
do
	if [ $x -eq 4 ]
	then
		echo "$x"
		echo "bad luck from China"
	elif [ $x -eq 9 ]
	then
		echo "$x"
		echo "bad luck from Japan"
	elif [ $x -eq 17 ]
	then
		echo "$x"
		echo "bad luck from Italy"
	else
		echo "$x"
	fi
	(( x++ ))
done
