#!/usr/bin/env bash
# This script displays the content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed


# A SOLUTION THAT WORKS, I LOVE YOU COPY-PASTER :)
# for file in *; do
# 	echo "$file" | cut -d '-' -f 2-
# done

files=$(ls)
for file in $files;
do
	if [[ $file == .* ]];
	then
		continue
	fi
	name_part=$(echo "$file" | cut -d '-' -f 2-)
	echo "$name_part"
done