#!/usr/bin/env bash
# Script that configures an Ubuntu server

# Backup the original file
sudo cp /etc/hosts ~/hosts.new

# Change the resolution of localhost and facebook.com
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts