#!/usr/bin/env bash
# Script that displays all active IPv4 IPs on the machine it’s executed on.

# Get the active IPv4 IPs
ips=$(ip -4 addr show | grep inet | awk '{print $2}' | cut -d'/' -f1)

# Display the IPs
echo "$ips"